version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: my-postgres-db
    hostname: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: multi_tenant_db
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-app-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: my-rabbitmq-broker
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my-app-network
    restart: unless-stopped
volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
networks:
  my-app-network:
    driver: bridge